-- THIS APPLICATION IS BASED ON SCHEMA FIRST SO WE DONT NEED TO ADD ANY MIGRATION SUPPORT FOR AUTO DDL
-- WE NEED TO CREATE DATABASE AND TABLE MANUALLY BY USING THIS SCRIPT

CREATE DATABASE NEXWARE;
DROP TABLE IF EXISTS `Palindrome`;
create table Palindrome(id BIGINT(10) NOT NULL AUTO_INCREMENT primary key,
                        list varchar(100) not null, UNIQUE KEY(list));
